#! /bin/bash
#SBATCH --mail-user=<anthony.hauser@unisante.ch>
#SBATCH --mail-type=END,FAIL
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=2G
#SBATCH --array=1-1
#SBATCH -c 10
#SBATCH --output="outfiles/slurm-%A_%a.out"


# Create paths, job number and date of job
PROJECT="causes-of-deaths/cluster"
JOB1="${SLURM_ARRAY_JOB_ID}"
JOB2=${SLURM_ARRAY_TASK_ID}
Rfile="run_mod4"
date="20241114"

# Sweeping parameters_mod_ind.txt
N=${SLURM_ARRAY_TASK_ID}
echo "$N"

ra=`head -n ${N} parameters_mod.txt | tail -n 1 | cut -d' ' -f1`
rb=`head -n ${N} parameters_mod.txt | tail -n 1 | cut -d' ' -f2`
rc=`head -n ${N} parameters_mod.txt | tail -n 1 | cut -d' ' -f3`
rd=`head -n ${N} parameters_mod.txt | tail -n 1 | cut -d' ' -f4`
re=`head -n ${N} parameters_mod.txt | tail -n 1 | cut -d' ' -f5`
rf=`head -n ${N} parameters_mod.txt | tail -n 1 | cut -d' ' -f6`
rg=`head -n ${N} parameters_mod.txt | tail -n 1 | cut -d' ' -f7`
rh=`head -n ${N} parameters_mod.txt | tail -n 1 | cut -d' ' -f8`

# Paths to temporary file and out file
SCR="/users/ahauser6/${PROJECT}/temp-$Rfile-$date-$ra-$rb-$rc-$rd-$re-$rf-$rg-$rh"
echo "SCR: $SCR"
OUT="/users/ahauser6/${PROJECT}/outfiles/$Rfile-$date-$ra-$rb-$rc-$rd-$re-$rf-$rg-$rh.Rout"
echo "OUT: $OUT"

# Display
echo "Job array item $N: ra=$ra, rb=$rb, rc=$rc, rd=$rd, re=$re, rf=$rf, rg=$rg, rh=$rh"
echo "---------------------------------"

# Create temporary file, where the simulations are run
mkdir -p $SCR
cp -p "$Rfile.R" $SCR/.
cd $SCR

# Load module 
module purge
dcsrsoft use 20240303
module load r-light

echo "---------------------------------"


# Run R file
R CMD BATCH --no-save --no-restore "--args $ra $rb $rc $rd $re $rf $rg $rh $date" "$Rfile.R"

echo "---------------------------------"


# Copy Rout file
cp "$Rfile.Rout" $OUT
rm "$Rfile.Rout"
rm -rf $SCR

echo "Job is done."
