#! /bin/bash
#SBATCH --mail-user=<anthony.hauser@iplesp.upmc.fr>
#SBATCH --mail-type=END,FAIL
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=6G
#SBATCH --array=1-24
#SBATCH -c 10
#SBATCH --partition=normal
#SBATCH --output="outfiles/slurm-%A_%a.out"
#SBATCH --exclude=compute-2-0


# # --nodelist=compute-1-1
# # -w "compute-1-1"
# # --nodelist="compute-1-1"
# # --partition=normal
# # --error="outfiles/slurm-%A_%a.err"
# # --cpus-per-task=4

# Create paths, job number and date of job
PROJECT="contact_matrix/cluster"
JOB1="${SLURM_ARRAY_JOB_ID}"
JOB2=${SLURM_ARRAY_TASK_ID}
Rfile="run_mod_ind"

# Sweeping parameters_mod_ind.txt
N=${SLURM_ARRAY_TASK_ID}
echo "$N"

ra=`head -n ${N} parameters_mod_ind.txt | tail -n 1 | cut -d' ' -f1`
rb=`head -n ${N} parameters_mod_ind.txt | tail -n 1 | cut -d' ' -f2`
rc=`head -n ${N} parameters_mod_ind.txt | tail -n 1 | cut -d' ' -f3`
rd=`head -n ${N} parameters_mod_ind.txt | tail -n 1 | cut -d' ' -f4`
re=`head -n ${N} parameters_mod_ind.txt | tail -n 1 | cut -d' ' -f5`
rf=`head -n ${N} parameters_mod_ind.txt | tail -n 1 | cut -d' ' -f6`
rg=`head -n ${N} parameters_mod_ind.txt | tail -n 1 | cut -d' ' -f7`
rh=`head -n ${N} parameters_mod_ind.txt | tail -n 1 | cut -d' ' -f8`
date="20240620"

# Paths to temporary file and out file
SCR="/home/hauser/${PROJECT}/temp-$Rfile-$date-$ra-$rb-$rc-$rd-$re-$rf-$rg-$rh"
echo "SCR: $SCR"
OUT="/home/hauser/${PROJECT}/outfiles/$Rfile-date-$ra-$rb-$rc-$rd-$re-$rf-$rg-$rh.Rout"
echo "OUT: $OUT"

# Display
echo "Job array item $N: ra=$ra, rb=$rb, rc=$rc, rd=$rd, re=$re, rf=$rf, rg=$rg, rh=$rh"
echo "---------------------------------"

# Create temporary file, where the simulations are run
mkdir -p $SCR
cp -p "$Rfile.R" $SCR/.
cd $SCR

# Load module 
module load R/4.3.2-openblas

echo "---------------------------------"


# Run R file
R CMD BATCH --no-save --no-restore "--args $ra $rb $rc $rd $re $rf $rg $rh $date" "$Rfile.R"

echo "---------------------------------"


# Copy Rout file
cp "$Rfile.Rout" $OUT
rm "$Rfile.Rout"
rm -rf $SCR

echo "Job is done."
