#! /bin/bash
#SBATCH --mail-user=<anthonyhauser06@gmail.com>
#SBATCH --mail-type=END,FAIL
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=10G
#SBATCH --array=1-35
#SBATCH -c 4
#SBATCH --output="outfiles/slurm-%A_%a.out"


# Create paths, job number and date of job
PROJECT="causes-of-deaths/cluster"
JOB1="${SLURM_ARRAY_JOB_ID}"
JOB2=${SLURM_ARRAY_TASK_ID}
Rfile="run_corr_resp_lag_post"
date="20241218"

# Sweeping parameters_mod_ind.txt
N=${SLURM_ARRAY_TASK_ID}
echo "$N"

ra=`head -n ${N} parameters_mod_corr.txt | tail -n 1 | cut -d' ' -f1`
rb=`head -n ${N} parameters_mod_corr.txt | tail -n 1 | cut -d' ' -f2`

# Paths to temporary file and out file
SCR="/users/ahauser6/${PROJECT}/temp-$Rfile-$date-$ra-$rb"
echo "SCR: $SCR"
OUT="/users/ahauser6/${PROJECT}/outfiles/$Rfile-$date-$ra-$rb.Rout"
echo "OUT: $OUT"

# Display
echo "Job array item $N: ra=$ra, rb=$rb"
echo "---------------------------------"

# Create temporary file, where the simulations are run
mkdir -p $SCR
cp -p "$Rfile.R" $SCR/.
cd $SCR

# Load module 
module purge
dcsrsoft use 20240303
module load r-light

echo "---------------------------------"


# Run R file
R CMD BATCH --no-save --no-restore "--args $ra $rb $date" "$Rfile.R"

echo "---------------------------------"


# Copy Rout file
cp "$Rfile.Rout" $OUT
rm "$Rfile.Rout"
rm -rf $SCR

echo "Job is done."
